apiVersion: v2
name: hugo-hoster
description: A Helm chart for hosting hugo blogs in Kubernetes with S3 to serve the static content.
type: application

version: "0.0.5"
appVersion: "0.0.2"

maintainers:
  - name: cedi
    url: https://cedi.dev

sources: 
  - https://github.com/hugo-hoster/hugo-hoster

home: https://github.com/cedi/hugohoster-api


keywords:
  - hugo
  - staticpage
  - html
  - hosting

kubeVersion: '>=v1.23.0-0'